### ISSUE TITLE
Question about learning rate in FedNova algorithm.

### ISSUE THREAD

**Issue by zhaoxing-zstar** [Xtra-Computing/NIID-Bench#10]
Hi, your implementation is good. The FedAvg algorithm in the original paper [https://arxiv.org/pdf/2007.07481.pdf](https://arxiv.org/pdf/2007.07481.pdf) includes the learning rate $\eta$ both in computing normalized gradients and global updates, but this term doesn't seem to appear in your code. I‘m wondering if there are things I missed or the learning rate should be added  here.
<img width="662" alt="屏幕截图 2022-07-12 205640" src="https://user-images.githubusercontent.com/60384317/178496396-160441a0-d72c-4e46-862e-1bc0db849c85.png">
<img width="647" alt="屏幕截图 2022-07-12 205735" src="https://user-images.githubusercontent.com/60384317/178496403-75483c6a-509a-4c07-a1af-66ac342150f6.png">

**Comment by sjtudyq** [comment]
Thanks for your question. Look at the algorithm Line 3 & Line 12. I think these two $\eta$ can be cancelled out, isn't it?

**Comment by zhaoxing-zstar** [comment]
> Thanks for your question. Look at the algorithm Line 3 & Line 12. I think these two $\eta$ can be cancelled out, isn't it?

Quite right, thanks.
