### ISSUE TITLE
Probably a mistake in experiments.py

### ISSUE THREAD

**Issue by MacroMicroMichael** [Xtra-Computing/NIID-Bench#12]
Thanks for your work.  I think there is probably a small mistake in line 673 of experiments.py. According to the pseudocode of SCAFFOLD, the denominator here should be the number of all clients instead of the number of selected clients per round. Please correct me if I 'm wrong. Thank you!

**Comment by sjtudyq** [comment]
Yeah, I think you are right. I have revised the denominator to `args.n_parties` the line 673. Thank you very much for pointing out :)

**Comment by MacroMicroMichael** [comment]
No problem! I have just started working on the area of federated learning and your work really help me a lot.
