### ISSUE TITLE
Noise-based feature imbalance的配图是不是有问题

### ISSUE THREAD

**Issue by kevin-collins** [Xtra-Computing/NIID-Bench#14]
因为Fednova比Fedavg低了四个千，fedavg比fedprox低了四个千，SCAFFOLD远高于其他方法，但是图上，fednova是比较低的，而另外三种方法的线很接近，似乎和数据不符

**Comment by sjtudyq** [comment]
Thanks for your attention on our work! Note that the accuracy shows the average of three experiments, while the training curve is based on only one experiment. Thus, there may be some difference. Maybe that explains your question.
