### ISSUE TITLE
Problem in running experiments.py

### ISSUE THREAD

**Issue by paprika0741** [Xtra-Computing/NIID-Bench#17]
Hello， thank you for your nice code. 
Maybe here shoulbe be "default='mlp'" instead of  "default='MLP'" 
https://github.com/Xtra-Computing/NIID-Bench/blob/b56de2aab2ea96edb638b86be0a5833ee73240ce/experiments.py#L27

**Comment by sjtudyq** [comment]
Thanks a lot for pointing out! Have changed.
