### ISSUE TITLE
len(dataloder) and len(dataset)

### ISSUE THREAD

**Issue by paprika0741** [Xtra-Computing/NIID-Bench#18]
https://github.com/Xtra-Computing/NIID-Bench/blob/e22b4210aa5e645bfcb0ecad41e28a9c673aff68/experiments.py#L725

Number of local samples $|D^i|$ =len(train_dl_local.dateset) instead  of len(train_dl_local).
Although the batch size is the same for all  dataloader，there will be cases where the number of data cannot be divided by the batch size. 
I think this will be a little different from the pseudo-code

**Comment by sjtudyq** [comment]
Thank you very much for helping improving our code! Have revised :)
