### ISSUE TITLE
Error in running  experiments.py with args.alg == 'all_in'

### ISSUE THREAD

**Issue by paprika0741** [Xtra-Computing/NIID-Bench#19]
Hi, when I run the following command
`
python experiments.py --model=simple-cnn --dataset=cifar10  --alg=all_in   --lr=0.01  --batch-size=64    --epochs=10      --n_parties=10    --rho=0.9    --comm_round=50      --partition=noniid-labeldir      --beta=0.5     --device=cuda:0    --datadir=./data/      --logdir=./logs/      --noise=0     --init_seed=0
`
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

Maybe this line of code should be preceded by "nets[0].to(device)"
https://github.com/Xtra-Computing/NIID-Bench/blob/885648ae2bc7a4a448c7ff1979593c21a8ea1d1c/experiments.py#L1218

**Comment by sjtudyq** [comment]
Many thanks for pointing it out! Have fixed :)
