### ISSUE TITLE
parser.add_argument('-load_path', required=True, help='Checkpoint to load path from')

### ISSUE THREAD

**Issue by liyang-good** [Xtra-Computing/NIID-Bench#2]
HI，I want to know how i find "-load_path" ?

Thanks

**Comment by sjtudyq** [comment]
Hi! Thank you for your question and attention to our project! I review the code and actually I do not think the "mnist-generate.py" file has impact on our benchmark. We are going to delete it. You can safely ignore it. Thanks!

**Comment by liyang-good** [comment]
![image](https://user-images.githubusercontent.com/71406269/114831115-965f9580-9dff-11eb-829d-4784d08d1198.png)

This fig is gengerated by mnist_generated.py  ?    

 i  modify this command :parser.add_argument('-load_path', required=True, default='./checkpoints', help='Checkpoint to load path from') , however, it's not useful.

**Comment by sjtudyq** [comment]
Figure 5 is not generated by mnist_generate.py. Actually we find that mnist_generate.py is not useful in our benchmark. You can just remove it and the other files work.

**Comment by liyang-good** [comment]
Thanks .  i try it.  Your project is perfect!
