### ISSUE TITLE
Question about is_same_initial 

### ISSUE THREAD

**Issue by paprika0741** [Xtra-Computing/NIID-Bench#20]
This parameter is not involved in the pseudocode.
When t = 0, global model $\omega^0$ is sent to all the selected clients.
![image](https://user-images.githubusercontent.com/78540817/208090902-d1253283-fc32-47ef-95f3-3752d6771f26.png)

**Comment by sjtudyq** [comment]
Thanks for the question. The default setting is to use the same initialization. We decide to keep the `is_same_initial` for users to try different initializations on different parties.
