### ISSUE TITLE
Problem when running experiments.py

### ISSUE THREAD

**Issue by b856741** [Xtra-Computing/NIID-Bench#21]
Hi, when I tried to run experiments.py in default setting, there is a problem showed up
![1672149965986](https://user-images.githubusercontent.com/22851308/209678701-19ce01c4-cddb-42d4-8a99-6d48996a8a28.jpg)
is there any way to fix it?

**Comment by sjtudyq** [comment]
Well, for the default MNIST dataset, we do not set any MLP structure for it. We suggest to use our ``run.sh`` (simple-cnn) to run the experiments of MNIST. If you still want to use MLP for MNIST, you can set its structure.

**Comment by b856741** [comment]
when I tried it in cifar10 and simple-cnn
it executes as this
![1672173918269](https://user-images.githubusercontent.com/22851308/209720586-7f09004c-a02f-4039-a9a0-502ff15c924b.jpg)
it's been showing a lot of lines "`files already downloaded and verified`" after running an hour and it seems to be infinity, is it normal?

**Comment by sjtudyq** [comment]
It is normal. The running results are in the logging file.

**Comment by b856741** [comment]
I see, but when it finished and I checked the logs dir, why the files are 0KB?

    在 2022年12月28日 星期三 上午09:01:49 [GMT+8]， ***@***.***> 寫道：  
 
 


It is normal. The running results are in the logging file.

**Comment by b856741** [comment]
![1672205224413](https://user-images.githubusercontent.com/22851308/209763019-cf8fb4b0-5488-4cbc-8aa0-3efc5bcca037.jpg)

**Comment by sjtudyq** [comment]
I'm not sure what happens in your device. I just clone the current version and run the ``run.sh``. It seems normal in my side. 
![微信图片_20221228154837](https://user-images.githubusercontent.com/48618508/209777906-1db7b5be-592e-491a-99bd-8b876f84e771.png)

**Comment by ShuvoSahaRoy** [comment]
I am facing the same issue. You need to update the requirements.txt file properly. It's not working with A9a dataset too
