### ISSUE TITLE
Question about building test_dl_global when adding noise

### ISSUE THREAD

**Issue by paprika0741** [Xtra-Computing/NIID-Bench#23]
The test_ds_local is loaed by `test_ds = dl_obj(datadir+'./val/', transform=transform_test)`. 
Therefore, test_ds  is the same for all clients.  
https://github.com/Xtra-Computing/NIID-Bench/blob/692569f790af0f5908dba23a15d4d80ce7e7aec4/utils.py#L771
When adding noise，test_all_in_ds is  made by just concatenateing all the same test_ds  together. 
I don't understand the meaning of this.

https://github.com/Xtra-Computing/NIID-Bench/blob/692569f790af0f5908dba23a15d4d80ce7e7aec4/experiments.py#L860

**Comment by sjtudyq** [comment]
Thanks for the question. By our design, the test set is also added with different levels of noise to simulate the feature skews. If you want to try the normal test set, you can use the same setting as noise=0.
