### ISSUE TITLE
Question about partition method 'homo'

### ISSUE THREAD

**Issue by paprika0741** [Xtra-Computing/NIID-Bench#24]
When setting partition='homo',  for the same label, different clients have different numbers, even tens of differences .
The picture below is the heat map for the mnist dataset divided evenly among 10 clients  using partition method 'homo'.
![image](https://user-images.githubusercontent.com/78540817/225918179-76ee911c-4214-4fb0-ba63-a10517c9c0e2.png)

**Comment by sjtudyq** [comment]
The samples are randomly permutated and selected, so our procedure conducts an IID sampling. From the statistics, it is quite IID. If you want to divide each class with exactly the same number of samples, it can be done by slightly changing the code. However, I don't think IID must be exactly the same, and in reality it is almost impossible to be exactly the same.
