### ISSUE TITLE
Feature skew distribution code not present in `partition.py`

### ISSUE THREAD

**Issue by aritroCoder** [Xtra-Computing/NIID-Bench#29]
The feature imbalances discussed in Readme are:
- Quantity-based label imbalance: partition=noniid-#label1, noniid-#label2 or noniid-#label3
- Distribution-based label imbalance: partition=noniid-labeldir, beta=0.5 or 0.1
- Noise-based feature imbalance: partition=homo, noise=0.1 (actually noise does not affect net_dataidx_map)
- Synthetic feature imbalance & Real-world feature imbalance: partition=real
- Quantity Skew: partition=iid-diff-quantity, beta=0.5 or 0.1
- IID Setting: partition=homo
- Mixed skew: partition = mixed for mixture of distribution-based label imbalance and quantity skew; partition = noniid-labeldir and noise = 0.1 for mixture of distribution-based label imbalance and noise-based feature imbalance.

There are few issues with it.
- For Noise-based feature imbalance if noise does not affect net_dataidx_map then how can we say this is a different feature distribution than pure IID?
- Synthetic feature imbalance & Real-world feature imbalance where partition = real is not implemented
- Mixed skew is not implemented.

It could be great if these algorithms would get implemented, or atleast we get a pseudocode to see how to implement them. As it would be very useful for literature surveys for future works in non IID data distribution since not many works actually talk about feature skew.

**Comment by sjtudyq** [comment]
Thanks for your questions and interest in our project! 

For noise-based feature imbalance, the noise affects the data in different clients. The partition itself cannot simulate feature imbalance. 

For real-world and mixed skew partition, please refer to ``utils.py``. Search ``real`` and ``mixed``, to see the implementations.
