### ISSUE TITLE
scaffold's loss is nan

### ISSUE THREAD

**Issue by leondada** [Xtra-Computing/NIID-Bench#3]
Thanks for your contribution, it is useful to me
When I change the mlp model to a bigger one , I find that scaffold's loss is 'nan' after several rounds, do you have any idea for this issue?

**Comment by leondada** [comment]
One way to alleviate is ：
408 line in experiments.py ,   (cnt * args.lr)-->(args.epochs*cnt * args.lr)

But this does not completely solve this problem ...

**Comment by sjtudyq** [comment]
Thanks for your question! Actually we have encountered 'nan' issue for scaffold in some of our experiments, especially in the setting of quantity skew. Therefore you may see low accuracy and high variance of scaffold in some of our result table. From our observation, it seems that scaffold is unstable especially in parties with huge amount of data. Our training curve also shows that generally scaffold has faster convergence rate, but not stable enough in some settings. Maybe in further studies, we can explore why scaffold behaves such way and try to improve it.
