### ISSUE TITLE
logdir

### ISSUE THREAD

**Issue by liyang-good** [Xtra-Computing/NIID-Bench#4]
Hi, i want to know lodfir  is what?

![image](https://user-images.githubusercontent.com/71406269/120058592-9c8f9580-c07e-11eb-9522-4f6da79af6b9.png)

**Comment by sjtudyq** [comment]
It means the path to save logging file of experiments.

**Comment by sjtudyq** [comment]
For this picture, if we write everything in a line, maybe we do not need '\' there. I think '\' is needed when we put one command into several lines. Please try deleting all '\' there to see if it works.

**Comment by liyang-good** [comment]
Thanks ,  我应该设置logdir 是什么呢？
![image](https://user-images.githubusercontent.com/71406269/120067245-0cb51000-c0ad-11eb-83d3-23f7f11fb7dd.png)

**Comment by sjtudyq** [comment]
We have changed 'logdir' to optional parameter (line 42, experiment.py). Please try use the default value then. Hope that would help. Thanks!

**Comment by liyang-good** [comment]
thanks, it can run, i want to know why wait for a long time ?
![image](https://user-images.githubusercontent.com/71406269/120070004-60c6f100-c0bb-11eb-8aa9-a4636f7aa124.png)

**Comment by liyang-good** [comment]
Thanks, i can see result  in logs folder.  your job is well !
