### ISSUE TITLE
An issue about Scaffold

### ISSUE THREAD

**Issue by WwZzz** [Xtra-Computing/NIID-Bench#8]
Hi! I've read your paper 'Federated Learning on Non-IID Data Silos: An Experimental Study' and 'Model-Contrastive Federated Learning'. I think both works are very interesting!

However, I notice that the performance of Scaffold is unstable and even extremely poor (e.g. nan) in some cases of your implementation. I've also found that Scaffold is reliably stable and outperforms many baselines across different settings of data heterogeneity and datasets in other works like FedDyn (ICLR 2021), FedDC (CVPR2022). Therefore, I carefully read the source code of yours and found the controlling variable is not initialized as described in 'SCAFFOLD: Stochastic Controlled Averaging for Federated Learning' in Sec.4. Since a random initialization of controlling variable is meaningless and can be misleading when locally training the model (especially at the early stage of training), I wonder whether this is the reason accounting for the unstablility and poor performance of Scaffold.   

<img width="446" alt="image" src="https://user-images.githubusercontent.com/20792079/165934714-5aa5c7a0-8977-463f-ab49-38be300aa12b.png">

<img width="299" alt="image" src="https://user-images.githubusercontent.com/20792079/165934075-9c70a9e0-4a28-4a3f-bf93-fcdc8485a19c.png">

**Comment by WwZzz** [comment]
Another small difference is the update rule of the global controlling variable. The original weight of `dc` is |S|/N, and  the implementation is 1/|S|. The two weights can be different in some cases:  when N>>S and S is small, the latter one would be larger.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/20792079/165981262-243da3a7-0f6e-48b9-b6ef-2a40a59d55f6.png">

<img width="88" alt="image" src="https://user-images.githubusercontent.com/20792079/165981333-e7654e0d-0bc1-4a15-b06d-dda4b54ae1b5.png">

**Comment by sjtudyq** [comment]
Thanks for your question! As shown in your screenshot of our code, we set the initial c_local to the parameters of initial c_global in a loop. From the Algorithm 1 of the SCAFFOLD paper, as long as $c_i-c$ is equal to zero, whether initializing the controlling variables to zero or not does not change the behavior of training.

We also conduct a simple experiment to verify it. We print the value of c_global and c_local after the first round and find that they are the same with or without initializing to zero.

**Comment by WwZzz** [comment]
Thanks for your reply! It does help me a lot.
